name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install dependencies
      - name: "Install dependencies"
        run: |
          # update package manager...
          sudo apt-get -y update ; sudo apt-get -y upgrade
          # install gcc...
          sudo apt-get install -y build-essential
          # install clang...
          sudo apt-get install -y clang

      # check compilation status
      - name: "Test no.0: Compilation status"
        run: |
          set -x

          # test C modules...
          gcc   -Wall -Wextra -Werror -std=c99 tests/00-compile.c -lm
          clang -Wall -Wextra -Werror -std=c99 tests/00-compile.c -lm
          
          # test C++ modules...
          g++     -Wall -Wextra -Werror -std=c++11 tests/00-compile.cc -lm
          clang++ -Wall -Wextra -Werror -std=c++11 tests/00-compile.cc -lm
      
      # check vec2 module
      - name: "Test no.1: vec2 module"
        run: |
          set -x

          # test C modules...
          gcc   -Wall -Wextra -Werror -std=c99 tests/01-vec2.c -lm
          ./a.out && rm -f a.out
          
          clang -Wall -Wextra -Werror -std=c99 tests/01-vec2.c -lm
          ./a.out && rm -f a.out
          
          # test C++ modules...
          g++     -Wall -Wextra -Werror -std=c++11 tests/01-vec2.cc -lm
          ./a.out && rm -f a.out
          
          clang++ -Wall -Wextra -Werror -std=c++11 tests/01-vec2.cc -lm
          ./a.out && rm -f a.out
